
FROM debian:wheezy

ENV DEBIAN_FRONTEND noninteractive

MAINTAINER Sebastian Krohn <seb@gaia.sunn.de>

RUN apt-get -y update
RUN apt-get -y upgrade && apt-get -y install apt-utils lsb-release
RUN apt-get clean

